version: '3.9'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: cache
    ports: 
      - '6379:6379'
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass jasonrocks"
    volumes:
      - ./redis_data:/data
  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ekoloji

  spring-cache:
    image: spring-cache
    container_name: spring-cache
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ekoloji
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=jasonrocks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
      - cache
