spring:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
               
  jackson:
    serialization:
      fail-on-empty-beans: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      unwrap-root-value: false

  profiles:
    active:
    - dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    password: ${SPRING_REDIS_PASSWORD}
    timeout: 10000ms

  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false
---
spring:
  config: 
    activate:
      on-profile: "dev" 
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
server:
  port: 8080

---

clear:
  all:
    cache:
      fixed:
        rate: 

management:
  endpoints:
    web:
      exposure:
        exclude: "*"
                  
  endpoint:
    shutdown:
      enabled: true
