version: '3.9'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: cache
    hostname: cache
    ports: 
      - '6379:6379'
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass jasonrocks"
    volumes:
      - ./redis_data:/data

  cassandra1:
    image: 'bitnami/cassandra:latest'
    environment:
      - CASSANDRA_CLUSTER_NAME=test
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=jph
#  this is actually hardcoded with SIMPLE Snitch
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_HOST cassandra1
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - '9042:9042'
      - '9160:9160'
    volumes:
      - ./cassandra:/bitnami
      - ./cassandra_init:/docker-entrypoint-initdb.d

  spring-cache:
    image: spring-cache
    container_name: spring-cache
    hostname: spring-cache
    environment:
      - SPRING_CASSANDRA_HOST=cassandra1
      - SPRING_CASSANDRA_PORT=9042
      - SPRING_CASSANDRA_USER=cassandra
      - SPRING_CASSANDRA_PASSWORD=jph
      - SPRING_CASSANDRA_CLUSTER=test
      - SPRING_CASSANDRA_DATACENTER=datacenter1
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=jasonrocks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - cassandra1
      - cache
