version: '3.9'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: cache
    hostname: cache
    ports: 
      - '6379:6379'
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass jasonrocks"
    volumes:
      - ./redis_data:/data

  cassandra1:
    image: 'bitnami/cassandra:latest'
    environment:
      - CASSANDRA_CLUSTER_NAME=test
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=jph
#  this is actually hardcoded with SIMPLE Snitch
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_HOST cassandra1
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - '9042:9042'
      - '9160:9160'
    volumes:
      - ./cassandra:/bitnami
      - ./cassandra_init:/docker-entrypoint-initdb.d
